spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_openfeign
    username: postgres
    password: krya
    driver-class-name: org.postgresql.Driver
  application:
    name: address-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Set to true to display SQL queries in the console

server:
  port: 8081
  servlet:
    context-path: /address-service